### ISSUE TITLE
[mac] tray windows is not coming on front

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/tray#102]

**Comment by Lezh1k** [comment]
Test scenario:
1. Launch tray application.
2. Log in
3. Launch settings dialog
4. Launch about dialog
5. Launch generate ssh dialog. 
6. Try to switch between those windows via tray menu. Means push menu item "About" in menu. 

Expected result: 
You should see switched dialog on top and it should be focused

**Comment by asanaliev** [comment]
I am also getting this issues on Mac OS 10.11.5, with the latest version of Tray.

**Comment by Lezh1k** [comment]
Fixed.
