### ISSUE TITLE
[Win] Сan't ssh after restart the system

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#103]
For replay this bug you need:

Test case
1) Create Environment
2) Add ssh key to Environment
3) Restart the System
4) Try ssh to created container

Result: can't ssh , get window 'Connection timed out'
![01-09-2016 15-45-42](https://cloud.githubusercontent.com/assets/11311924/18163175/e3250a4a-7063-11e6-8c30-2c0d81fd060e.jpg)

**Comment by btemir** [comment]
reproduced. cannot ssh to local container at all (after 24 hours) on win10
***************************************p2p debug on win host:
> C:\Users\tt\Desktop>p2p debug
> DEBUG INFO:
> Number of gouroutines: 21
> Instances information:
> Hash: swarm-a1415906-36bf-4ad0-8c95-800ae934f295
> ID: 92ef6df5-7523-11e6-8fee-022d0fae0f03
> Interface Local Area Network1, HW Addr: 00:ff:1b:1c:cb:d8, IP: 10.178.2.245
> Peers:
>         --- 92ee3d10-7523-11e6-8dc7-022d0fae0f03 ---
>                 HWAddr: 06:bd:88:45:c6:33
>                 IP: 10.178.2.1
>                 Endpoint: 192.168.253.247:44594
>                 Peer Address: 192.168.253.247:44594
>                 Proxy ID: 0
>         --- End of 92ee3d10-7523-11e6-8dc7-022d0fae0f03 ---
>         --- 7fb0dd1e-7516-11e6-8a7b-022d0fae0f03 ---
>                 HWAddr: 00:ff:7d:4c:a4:76
>                 IP: 10.178.2.246
>                 Endpoint: 54.93.164.238:42468
>                 Peer Address: 5.57.8.80:64070
>                 Proxy ID: 5
>         --- End of 7fb0dd1e-7516-11e6-8a7b-022d0fae0f03 ---
>         --- 7657cfc2-752c-11e6-8c8c-022d0fae0f03 ---
>                 HWAddr: 00:ff:0c:65:74:24
>                 IP: 10.178.2.245
>                 Endpoint: 192.168.253.130:56947
>                 Peer Address: 192.168.253.130:56947
>                 Proxy ID: 0
>         --- End of 7657cfc2-752c-11e6-8c8c-022d0fae0f03 ---
> 
********************************p2p debug on RH:
> (amd64)ubuntu@rh1473239108:/apps/subutai/current/bin$ ./p2p debug
> DEBUG INFO:
> Number of gouroutines: 25
> Instances information:
> Hash: swarm-a1415906-36bf-4ad0-8c95-800ae934f295
> ID: 92ee3d10-7523-11e6-8dc7-022d0fae0f03
> Interface p2p100, HW Addr: 06:bd:88:45:c6:33, IP: 10.178.2.1
> Peers:
>         --- 7657cfc2-752c-11e6-8c8c-022d0fae0f03 ---
>                 HWAddr: 00:ff:0c:65:74:24
>                 IP: 10.178.2.245
>                 Endpoint: 192.168.253.130:56947
>                 Peer Address: 192.168.253.130:56947
>                 Proxy ID: 0
>         --- End of 7657cfc2-752c-11e6-8c8c-022d0fae0f03 ---
>         --- 7fb0dd1e-7516-11e6-8a7b-022d0fae0f03 ---
>                 HWAddr: 00:ff:7d:4c:a4:76
>                 IP: 10.178.2.246
>                 Endpoint: <nil>
>                 Peer Address: 5.57.8.80:64070
>                 Proxy ID: 0
>         --- End of 7fb0dd1e-7516-11e6-8a7b-022d0fae0f03 ---

************************************ipconfig on win host:
```
C:\Users\tt\Desktop>ipconfig
Настройка протокола IP для Windows
Адаптер Ethernet Ethernet0:

   DNS-суффикс подключения . . . . . : localdomain
   Локальный IPv6-адрес канала . . . : fe80::fde1:fbc5:ab2e:9ba9%13
   IPv4-адрес. . . . . . . . . . . . : 192.168.253.240
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . : 192.168.253.2

Адаптер Ethernet VirtualBox Host-Only Network:

   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::e1a9:ad55:67c2:4a2%18
   IPv4-адрес. . . . . . . . . . . . : 192.168.56.1
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . :

Адаптер Ethernet Ethernet:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 2:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 3:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 4:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 5:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 6:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 7:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 8:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 9:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Адаптер Ethernet Ethernet 10:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

Туннельный адаптер isatap.localdomain:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . : localdomain

Туннельный адаптер Подключение по локальной сети* 3:

   DNS-суффикс подключения . . . . . :
   IPv6-адрес. . . . . . . . . . . . : 2001:0:5ef5:79fb:34c9:3308:fac6:f7af
   Локальный IPv6-адрес канала . . . : fe80::34c9:3308:fac6:f7af%10
   Основной шлюз. . . . . . . . . : ::

Туннельный адаптер isatap.{FD6D3918-FD32-486D-AFFA-D6884F0FC5E7}:

   Состояние среды. . . . . . . . : Среда передачи недоступна.
   DNS-суффикс подключения . . . . . :

```
**************************************ifconfig on RH:
(amd64)ubuntu@rh1473239108:/apps/subutai/current/bin$ ifconfig
00163e1623fb Link encap:Ethernet  HWaddr fe:0b:09:af:4e:65
          inet6 addr: fe80::fc0b:9ff:feaf:4e65/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1300  Metric:1
          RX packets:53 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28433 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3562 (3.5 KB)  TX bytes:1481400 (1.4 MB)

00163e17c6cd Link encap:Ethernet  HWaddr fe:68:c4:dc:b4:5e
          inet6 addr: fe80::fc68:c4ff:fedc:b45e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1300  Metric:1
          RX packets:67 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28439 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8292 (8.2 KB)  TX bytes:1483402 (1.4 MB)

00163e1d548b Link encap:Ethernet  HWaddr fe:f6:7b:d5:83:8b
          inet6 addr: fe80::fcf6:7bff:fed5:838b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1300  Metric:1
          RX packets:41 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28429 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2866 (2.8 KB)  TX bytes:1481178 (1.4 MB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:b2:67:4c
          inet6 addr: fe80::a00:27ff:feb2:674c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1363563 errors:0 dropped:0 overruns:0 frame:0
          TX packets:190090 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:606588051 (606.5 MB)  TX bytes:56670906 (56.6 MB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:9a:21:a1
          inet addr:10.0.3.15  Bcast:10.0.3.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe9a:21a1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6679 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6284 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3387835 (3.3 MB)  TX bytes:2028407 (2.0 MB)

eth2      Link encap:Ethernet  HWaddr 08:00:27:b7:78:0e
          inet addr:192.168.56.101  Bcast:192.168.56.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:feb7:780e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7533 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14020 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3411566 (3.4 MB)  TX bytes:2541159 (2.5 MB)

gw-100    Link encap:Ethernet  HWaddr 7e:da:aa:7c:f3:48
          inet addr:172.17.110.1  Bcast:172.17.110.255  Mask:255.255.255.0
          inet6 addr: fe80::7cda:aaff:fe7c:f348/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1300  Metric:1
          RX packets:96 errors:0 dropped:0 overruns:0 frame:0
          TX packets:98 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:11054 (11.0 KB)  TX bytes:11188 (11.1 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2443 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2443 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:264874 (264.8 KB)  TX bytes:264874 (264.8 KB)

management Link encap:Ethernet  HWaddr fe:40:95:1c:32:b7
          inet6 addr: fe80::fc40:95ff:fe1c:32b7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:210345 errors:0 dropped:0 overruns:0 frame:0
          TX packets:216151 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:53100076 (53.1 MB)  TX bytes:76768965 (76.7 MB)

mng-net   Link encap:Ethernet  HWaddr d2:3b:16:84:61:74
          inet addr:10.10.10.254  Bcast:10.10.10.255  Mask:255.255.255.0
          inet6 addr: fe80::d03b:16ff:fe84:6174/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:210345 errors:0 dropped:0 overruns:0 frame:0
          TX packets:216144 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:53100076 (53.1 MB)  TX bytes:76768407 (76.7 MB)

nat       Link encap:Ethernet  HWaddr 32:c0:fb:91:16:27
          inet addr:10.10.0.254  Bcast:10.10.0.255  Mask:255.255.255.0
          inet6 addr: fe80::30c0:fbff:fe91:1627/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:648 (648.0 B)

p2p100    Link encap:Ethernet  HWaddr 06:bd:88:45:c6:33
          inet addr:10.178.2.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::5052:2eff:fea2:6299/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1600  Metric:1
          RX packets:33 errors:0 dropped:0 overruns:0 frame:0
          TX packets:59 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:36540 (36.5 KB)  TX bytes:7932 (7.9 KB)

wan       Link encap:Ethernet  HWaddr 08:00:27:b2:67:4c
          inet addr:192.168.253.247  Bcast:192.168.253.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:feb2:674c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:308999 errors:0 dropped:14 overruns:0 frame:0
          TX packets:174191 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:69777856 (69.7 MB)  TX bytes:42684392 (42.6 MB)

**Comment by akylbekesenaliev** [comment]
Reproduced: Cannot ssh after restart : 
![image](https://cloud.githubusercontent.com/assets/17665678/18338794/40d94d3c-75bd-11e6-8992-e1a7c30139e1.png)
![image](https://cloud.githubusercontent.com/assets/17665678/18338809/56546f70-75bd-11e6-8658-ed4bcb798efd.png)
[win_info.txt](https://github.com/subutai-io/tray/files/460938/win_info.txt)
[p2p_log.txt](https://github.com/subutai-io/tray/files/460941/p2p_log.txt)

**Comment by btemir** [comment]
Tested on Win 8.1 and Win 7 - ssh connects after restart. Problem persists on Windows 10. Changing TAP-windows to 2.21.2 can resolve problem for Win 10.

**Comment by btemir** [comment]
Reason of this issue is error in setting IP address for interface:
 ![1](https://cloud.githubusercontent.com/assets/16958983/18416459/b59f8904-7826-11e6-8396-0f7f5f197000.PNG) 

Tests showed that is error appears when one of TAP interfaces already has this address (You can try 
`netsh interface ip set address "Ethernet x" static 10.x.x.245 255.255.255.0` on any of TAP interfaces, address find in p2p daemon logs.

Looks that `"C:\Program Files\TAP-Windows\bin\tapinstall.exe" remove tap0901` (part of deltapall.bat) does not delete all records from registry, so one of TAP interfaces has this IP, but You caqn not see it nor with `ipconfig /all` nor with ` netsh interface ip show addresses`. 
 To avoid this we can for example:
1. Use `.\devcon.exe find =net` and `:  .\devcon.exe -r remove "@ROOT\NET\0000"` for each interface, reliable but not preffered method as devcon is a part of Windows Kits and need to be installed (For manual test interfaces can be deleted using Device Manager)
2. Configure each TAP interface with fake address `netsh interface ip set address "Ethernet 8" static 10.x.x.117 255.255.255.0`. `netsh interface ip set address "Ethernet 8" dhcp` can not work. This method is working but looks nasty. May be better way to remove IP address from interface can be found.

Both methods can be used for manual test - just stop "Subutai Social P2P" service, delete or reconfigure all TAP interfaces and after that start service or run `p2p daemon`

Tested on VMWare Win 10.
