### ISSUE TITLE
After p2p update I can observe p2p icon on my Desktop 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#105]
![image](https://cloud.githubusercontent.com/assets/17665678/18194183/ab78c166-7105-11e6-878c-98f15d52f3ae.png)
To play the bug go to : 
Tray - > About - > P2P update 
result: 
P2P icon gets on desktop

**Comment by Lezh1k** [comment]
Test scenario : 
1. Get p2p.exe . That p2p.exe should not be the same as p2p.exe on kurjun. (ask developers to build it)
2. Create backup of that p2p.exe. (p2p.exe_back for example)
3. That p2p.exe should be located in standard path ("C:\Subutai\bin\p2p.exe") as I know. 
4. Launch tray application. 
5. Check tray->settings->commands. P2P command should be `p2p.exe` (default value).
6. Open about dialog.
7. Update tray. 
8. If update successful finished - check desktop. 

Expected result: 
There is no p2p icons on desktop.

**Comment by akylbekesenaliev** [comment]
Tested, its fixed now, closing the issue.
