### ISSUE TITLE
Can't add SSH key

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#106]
For replay this bug you need:

Test case
1) Create Environment
2) Generate SSH key via Tray
3) Paste SSH to Environment
a. Via button in Tray 'Add key to environmets'
b. Via Hub - Environments - "Environment" - SSH keys - 'Add SSH Key' button

Result:
You observe error:
a. 'Error transferring ... - server replied: Server error
b. 500 Internal server error
![10-09-2016 11-45-16](https://cloud.githubusercontent.com/assets/11311924/18408604/cd4c751c-775e-11e6-80e5-b2ba60cffda7.jpg)
![10-09-2016 11-44-37](https://cloud.githubusercontent.com/assets/11311924/18408605/cd7e4b82-775e-11e6-8c06-ab6678afc398.jpg)

**Comment by asanaliev** [comment]
Fixed and tested on prod. 
@NikolaiB please check.

**Comment by NikolaiB** [comment]
Manual adding (b) fixes - work correctly
Auto adding  (a) - the same error

**Comment by asanaliev** [comment]
Adding a key via Tray works correctly for me.

![image](https://cloud.githubusercontent.com/assets/7465404/18437013/dcab568a-791c-11e6-941c-67c29e6b8a8b.png)

![image](https://cloud.githubusercontent.com/assets/7465404/18437040/f603cb76-791c-11e6-9221-9f3e227fb0ca.png)

Please provide details of how you are testing. I will reproduce and fix.

**Comment by asanaliev** [comment]
The error with Tray for @NikolaiB is on Windows 10.

**Comment by NikolaiB** [comment]
Now auto adding also work correctly
![12-09-2016 19-49-26](https://cloud.githubusercontent.com/assets/11311924/18438195/830239c4-792a-11e6-854c-504350bfb563.jpg)

**Comment by NikolaiB** [comment]
Both methods now works normally.
