### ISSUE TITLE
Add a progress indicator showing Tray is starting

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#113]
**Background**
I updated Tray (from its About dialog) and clicked Yes when it asked "restart app?" After Tray was closed and didn't appear for sometime. I thought it just didn't started. But it might be that Tray needs some warm up period to start after update.

**Suggestion**
Show some progress indicator show that Tray is starting. Otherwise it may confuse users - they will think the app doesn't start or work.

**Comment by Lezh1k** [comment]
We will add some splash screen.
