### ISSUE TITLE
Tray menu: submenu on Linux

### ISSUE THREAD

**Issue by btemir** [subutai-io/tray#12]
Submenu works fine on windows. On Linux submenu is showed as one line. Adding actions runs submenu as window, but it is not what we want.

**Comment by btemir** [comment]
https://bugreports.qt.io/browse/QTBUG-49743. Resolved in 5.6.1.

**Comment by Lezh1k** [comment]
Waiting for qt 5.6.1. For now fixed by using submenu as window.
