### ISSUE TITLE
User must be able to deploy keys to specific environments

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#138]
0. Requirements: A user should be able to deploy to ALL, or to a specific SET of environments. The UI and Hub REST interfaces should provide this functionality so keys are not deployed everywhere since this might not be the intention of the user.
1. For the Hub side, the REST call that deploys the key to all environments probably iterates through all the environments of the user. This rest call can stay as-is and the Tray can use it when the user wants to deploy the key to all environments. We can add another rest call that specifies a target environment or a SET of environments to deploy keys to. Tray can pick the REST call based on what the user picks on the UI. This way we do not disrupt existing working functionality. Just need to copy and alter old rest call to consider set of environments.
2. The Tray can give two modes to the user in it's key deployment UI dialog. (a) deploy to all environments (existing functionality), (b) deploy to specific environments. The mode can be selected with a checkbox.
3. If the user selects to deploy to (default) specific environments (deploy all checkbox is not selected) then you can use a list widget with a right and left hand side. On the right side is selectable list of environments that you can deploy the key to. This right list should not include environments to which the key has already been deployed. The left side are the environments selected. When you select on right and transfer to left user selects specific set of environments to deploy to.
4. If you select deploy to all by checking the checkbox for the deploy all mode, then the widget for selecting specific environments clears and is greyed out (inactive).
5. The user should also be shown some progress, and errors should be reported to the user with logs reporting exactly which environments and containers the deployment failed on.

**Comment by akarasulu** [comment]
After this issue is closed, please create a new issue where we first specify how the Tray and the Hub can control deployment of keys to specific containers within an environment. Meaning you don't just deploy keys to all containers in the environment.

**Comment by Lezh1k** [comment]
Also we have to store information about ssh-keys and environments and use this information in ezssh process.

**Comment by Lezh1k** [comment]
We need 2 methods : 
1. Add key to environment
2. Check if several keys are presented in environment. Something like : 
check_keys_in_environment(list_of_keys, environment_id) . 
That method should return boolean array. For example if we have 1 and 3 keys presented in specified environment that method should return ["true", "false", "true"]. 
Tray needs it because of big overhead. 
@zubaidullo  could help with it.

**Comment by akarasulu** [comment]
@Lezh1k keep in mind that eventually we even want to control to which containers the keys are deployed. At present I don't think the Hub or even SS supports this.

**Comment by Lezh1k** [comment]
We need one more method for removing ssh key from environment. 
Something like this : void remove_keys_from_env(environment_id, array_of_ssh_keys) . 
@zubaidullo could help with it.
