### ISSUE TITLE
Give more information as feedback about warmup and setup progress

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#139]
According to Val:

> @akarasulu: created new env (SS) on peer installed~4 hrs ago. Warming period is longer that during the day (received "Cannot connect to swarm" error), after all TAP interfaces configured - started to connect. Keys uploaded.

Saying that we failed is wrong here. Instead we need to check on windows if the interface is up. If it is not ready we should say bringing up p2p interfaces warming up ... try again or actually inform when everything is ready to user so they may try again.

**Comment by amol4anoff** [comment]
Maybe make more informative messages about p2p connection.

**Comment by SEFI2** [comment]
Now, there three types of messages about environment status:

1. If `env` is unhealthy or under modification, then we show the status message of environment.
2. It is healthy, but can't join to swarm
   `The connection with environment is not established.`
3. It is healthy, but can't handshake with 
  `Can't connect to container.`

**Comment by SEFI2** [comment]
Moved to https://github.com/subutai-io/tray/issues/513
