### ISSUE TITLE
[Ubuntu] The About dialog shows "undefined" for some components

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#143]
On Ubuntu 16.04:

![image](https://cloud.githubusercontent.com/assets/7465404/20252651/3beb166e-aa4e-11e6-9020-16eb6a381eee.png)

In case of p2p, seems this is b/c of wrong path to p2p b/c I have p2p installed on that machine:

![image](https://cloud.githubusercontent.com/assets/7465404/20252678/7c4c187a-aa4e-11e6-99bf-c8d788d9afb3.png)

Correct path is: `/opt/subutai/p2p/bin/p2p`.

Suggestion: If a path to p2p is incorrect the Tray should give error message (notification) "_p2p client not found. Please verify p2p is installed and set correct path in Settings._"

**Comment by Lezh1k** [comment]
Fixed path in deb package.
