### ISSUE TITLE
When we cancel installation of P2P, CC shows not proper message. 

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/tray#1433]
When we cancel installation of P2P via CC on Mac, CC shows: "The P2P Daemon has been installed and will start running in a few seconds".  But actually P2P was not installed.  

How to reproduce:
1.  Click Install P2P via CC.
2. Proceed it.
3. When OS will ask to type your password to allow this, cancel.

**Comment by ibragim13kz** [comment]
Fixed in Master.
