### ISSUE TITLE
[Ubuntu] Changes in Settings are not saved

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#144]
On Ubuntu 16.04. I started tray via menu as normal user (not root):

![image](https://cloud.githubusercontent.com/assets/7465404/20252810/cba88bb4-aa4f-11e6-9151-1a6078eb5f99.png)

I changed p2p path:

![image](https://cloud.githubusercontent.com/assets/7465404/20252787/9709cd50-aa4f-11e6-9644-c090426ba216.png)

After restarting Tray, the path has old value.

**Comment by Lezh1k** [comment]
Can't reproduce by anybody. Looks like settings file corruption.
