### ISSUE TITLE
There is no icon on ubuntu dashboard.

### ISSUE THREAD

**Issue by eabyshev** [subutai-io/tray#148]
![screenshot from 2016-11-17 10 13 49](https://cloud.githubusercontent.com/assets/16954849/20376337/df3ddaaa-acaf-11e6-9459-eb38353cdac1.png)

![screenshot from 2016-11-17 10 32 20](https://cloud.githubusercontent.com/assets/16954849/20376492/404b7608-acb1-11e6-9896-99f994e876e9.png)

**Comment by akarasulu** [comment]
This should be a trivial fix. Let's get this done ASAP so it does not look ugly.
