### ISSUE TITLE
When installing tray on Linux the path to p2p is not correct

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#150]
I installed the Debian packages for Subutai p2p and tray in that order on an Ubuntu 16.04 system. The tray thought the p2p executable path was /opt/subutai/bin/p2p instead of using /opt/subutai/p2p/bin/p2p. This is a minor inconvenience and should be fixed because not everyone will realize how to fix it.

**Comment by Lezh1k** [comment]
Changed path in p2p.deb .
