### ISSUE TITLE
Fire off csshX with all containers in an environment when the csshX-ALL button is pressed for an environment

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#152]
I would love to be able to open up all the containers in the environment with csshX and be able to type commands that execute on all of them together. I think this should be really easy to do. Just have to assemble the string args for the SSH to each container.

I tried it manually but had to ssh into each container. Let's make this work with a special env button to SSH into them all 👍

**Comment by Lezh1k** [comment]
What should we use on linux and windows? 
Maybe it's better to make own tool like csshX ?

**Comment by akarasulu** [comment]
One already exists. Why should we redo this? I think what we can do is have some launch configuration setting that allows users to change the ssh executable and the parameters that you feed into it with variables?

**Comment by Lezh1k** [comment]
It's not good idea because somebody can get access to config file and make command like this : 
"ssh ip; sudo rm -rf /" . Even if we encrypt whole settings file user can be attacked like this.

**Comment by akarasulu** [comment]
This feature is a convenience feature for power users. It’s not something a babushka user would even know exists: heck they may never even use SSH. The feature makes it convenient for power users to launch clusterssh or CsshX for all containers in an environment without having to gather all the parameters needed for all the servers and the keys etc. This is a bit PITA for me and I use CsshX all the time with our environments. I realized this as a user.

Even power users on Windows can handle setting up all the plumbing like cygwin and clusterssh to make the feature work if they REALLY wanted it. But for the majority of non-power users on Windows who will be challenged, well fuck em. They don't need it anyways.

So instead of wasting time and energy implementing a nice qt-csshx like capability that is easy to use and requires no other configuration for the user, I think we should just leave this up to the user.

1. Create a configuration area in tray settings to specify the path to the CsshX or ClusterSSH executable. It's up to the power user to install, and configure their setup **NOT** the tray. 
2. The tray will check if the specified executable exists, and if it does will provide an extra menu item to "SSH to All" for each environment. If the executable file is not present and executable then these tray items will not appear on the dynamic environment submenus.
3. Use a switch statement to detect which executable and OS we're on to properly build the parameters for ClusterSSH or CsshX and then just launch the executable with those parameters.

IMHO this is the best balance for us. We don't have the time to implement everything we want in the perfect way. This is a non-critical minor enhancements for power users only and we can and must compromise.

**Comment by Lezh1k** [comment]
Right now we don't need cluster ssh, but it would be nice to have ability to fire ssh->all environment containers in one click.

**Comment by amol4anoff** [comment]
Fixed.
