### ISSUE TITLE
Launch menu should list peers available on Hub and on the LAN

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#167]
## UI Impact

This is what the Tray's Launch submenu looks like:

<img width="465" alt="screen" src="https://cloud.githubusercontent.com/assets/10051386/21963360/33ac5d94-db42-11e6-9b87-9cb8b1a0b17a.png">

The "**Launch SS console**" presumes there's a single local to the machine peer running. The menu item will go away. Instead we will have two new dynamic menu items:

 - Local Peers
 - Remote Peers

Each of these menus will list peers by human readable name. The names of peers will appear as menu subitems. The user can select the peer to launch a browser to that specific peer's SS console.

### Local Peers

These peers will be peers that are present on the local LAN. SSDP (Simple Service Discovery Protocol) which is used by RH's to discover local peers can be used by the Tray application to find Peers on the LAN. This way users need not configure anything.

### Remote Peers

The Hub will be used to get a list of peers owned by the user who is logged into the hub via the tray. Remote peers will be peers that are:

 - **NOT** present on the LAN
 - **AND** registered on the Hub

Some peers on the LAN may be registered so they might be returned from the listing provided by the Hub. **WARNING:** You will need to remove these local registered peers so they are not offered in duplicate on both menus.

**Comment by Lezh1k** [comment]
We also need to modify about dialog to make updates of RH and RH management possible.

**Comment by akarasulu** [comment]
> We also need to modify about dialog to make updates of RH and RH management possible.

Yes we can do these step by step.

**Comment by amol4anoff** [comment]
Fulfilled.
