### ISSUE TITLE
Open up related to notifcations windows when notifications are clicked 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#168]
![image](https://cloud.githubusercontent.com/assets/17665678/22014715/3d577ecc-dcc9-11e6-8772-802c8cb13ca7.png)

A suggestion: 

For users' convenience - I think it would be easier for users to respond to the Tray's notifications if this notifications would be clickable - meaning if notifcations are clicked then they should respond by opening up related windows, for example I have got a notification that says that Subutai management update is available so currently I will have to right click the Tray , go to About page and update my Management , but I think it would be easier and more comfortable for users if just by clicking on that notifcation the About page would come on. It might seem like a one click difference and like a small thing but I think we should be paying more attention to this kinda small processess because small things matter a lot, especiallly when it comes to this kinda user experience matters.

**Comment by akarasulu** [comment]
Great usability ideas !

**Comment by amol4anoff** [comment]
Done.
