### ISSUE TITLE
[Enhancement] Add up a popup window or a progress bar

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#176]
![image](https://cloud.githubusercontent.com/assets/17665678/23390295/5045ebc4-fd97-11e6-84f8-631e03296dfd.png)
I think we need to add up a progress bar/popup window to display for users and show them  that some process has taken place, because right now users dont know what is happening after they click Save Changes item. 
**Plus** maybe we also need a Clear item to clear up all the not needed SSH-Keys: 
Because this plenty of Keys might distract or confuse users later when they have a dozen of them: 
![image](https://cloud.githubusercontent.com/assets/17665678/23390358/ba3300a8-fd97-11e6-8674-eed800a90eb7.png)

**Comment by Lezh1k** [comment]
Done
