### ISSUE TITLE
[Hub side] Hub does not display real names of SSH keys 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#177]
![image](https://cloud.githubusercontent.com/assets/17665678/23390806/8acc1a4a-fd9a-11e6-8ba8-14e5faff356d.png)
[Hub side] Hub does not display real names of SSH keys and this will confuse users, to avoid confusion we have to make it easier for users to digest. Hub should display real names of SSH keys and Tray should also send the names of SSH keys.

**Comment by Lezh1k** [comment]
Done on tray side
