### ISSUE TITLE
Cross-compilation

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/tray#183]
We need to be able to build tray for all platforms on one ubuntu machine.

**Comment by Lezh1k** [comment]
Windows build is ready.

**Comment by p1gmale0n** [comment]
@Lezh1k what about status of this issue?
when we can migrate build process to jenkins?

**Comment by Lezh1k** [comment]
Paused because of
https://github.com/subutai-io/tray/issues/187 and https://github.com/subutai-io/tray/issues/185. 
Will continue work 1 May 2017.
