### ISSUE TITLE
[MacOS] Tray cannot identify software versions

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/tray#192]
seems p2p version related to #191

about chrome version logs have only
> Failed to wait for started process /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

![image](https://cloud.githubusercontent.com/assets/1177402/25844338/efff612a-34cb-11e7-82d7-ac6f62c4f549.png)

**Comment by p1gmale0n** [comment]
p2p version issue related to new path of p2p binary #191
rh version issue - tray should use `subutai-dev` and `subutai-master` commands for appropriate bnaches
mng version related to changed path to mng container on host's filesystem:
`cat /mnt/lib/lxc/management/opt/subutai-mng/etc/git.properties | grep git.build.version`
should be some like this
`cat /var/snap/$(snap list | grep subutai | cut -f 1 -d " ")/common/lxc/management/opt/subutai-mng/etc/git.properties | grep git.build.version`

**Comment by Lezh1k** [comment]
Done
