### ISSUE TITLE
Balance line in menu should lead user to the billing page in HUB 

### ISSUE THREAD

**Issue by soffokl** [subutai-io/tray#216]
![image](https://user-images.githubusercontent.com/8612618/29454680-de2d2c8a-842f-11e7-9c83-c3a5c08d36a1.png)

**Comment by samsonbek** [comment]
User's billing should open page `https://hub.subut.ai/users/<user ID>`
User's info could be obtained from `https://hub.subut.ai/rest/v1/tray/user-info`
@Lezh1k
