### ISSUE TITLE
Settings not saving unless vboxmanage is installed

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#233]
So I'm on a mint system running in KVM. I installed the snap straight onto it, and the tray. They're working now with the snap's p2p binary. However, because usability of the UI is not right, the tray forced me to do some pretty retarded things. 

How? I had to create this empty file and give it execute permissions to save the settings with the right p2p path:

> sudo touch /usr/bin/vboxmanage
> sudo chmod +x /usr/bin/vboxmanage 

Then I could save things. Also the message is horrible. You should say, cannot find the binary or it is not installed to the user. However user should be given an option to save anyway. You should not just be blocking the user. 

In general this is nice that it checks, but user should never be blocked from saving their settings and should be told and answer save anyway with the detected problems.

**Comment by Lezh1k** [comment]
Fixed
