### ISSUE TITLE
[Linux] Updates of p2p and tray not working in About dialog

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#234]
I think there might be permission issues here. @crioto I do not know if this is due to how the launcher is installing the tray now.

This is happening on most Linux systems tested. Last on was an Ubu 16.04.3 system.

**Comment by akarasulu** [comment]
Interesting steps:
(1) tried tray update, that worked
(2) after restart due to tray update the p2p update worked

**Comment by crioto** [comment]
I will review permissions

**Comment by akarasulu** [comment]
EZSSH does not seem to be working on the system.

**Comment by crioto** [comment]
I have check the permissions of installed files and they all belong to user `test2`. This excludes permission problems, so probably @Lezh1k can take a look at it and determine problem better.

Regarding p2p not being working - the service was down and this is a launcher's failure, so I will fix it

**Comment by Lezh1k** [comment]
Need to change folder permissions in deb package.
