### ISSUE TITLE
[Linux] [ud1704] After restart remember me information needs to be readded

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#256]
After a crash I noticed that I had to re-enter my account information when I had selected the **Remember me** button. Although not critical this is annoying.

**Comment by SEFI2** [comment]
Couldn't reproduce, need more details. Crashed the program by throwing the "1" on random line and looked reenter tray. Worked as expected.

**Comment by samsonbek** [comment]
I had same problem. Reason was that my OS user lost write permission to file `/opt/subutai/bin/subutai_tray.ini`. After I gave write permissions to this file, `remember me` started working.
