### ISSUE TITLE
Tray should give messages if p2p not present or inoperable with unhealthy p2p debug output

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#259]
Right now many people will make the mistake of installing the tray thinking it works when p2p is not installed. We need to make sure the user gets the appropriate messages from the tray. 

If the p2p daemon is not found it should say:

> Can't operate without the p2p daemon. Either change the path setting in __Settings__ or install the daemon it is not installed. You can get the [production|dev|stage] daemon from [here](https://cdn.subut.ai:8338/kurjun/rest/raw/get?name=subutai-p2p.pkg). 

The here part will be a link to the package for the respective OS and staging area in the CDN. 

If p2p is found but p2p debug shows that it is not working we need to give a message like this:

> Your p2p daemon ($PATH_TO_DAEMON) is inoperative. It is either misconfigured or installed incorrectly or both. Please contact us on [Slack](https://subutai-io.slack.com) or file an issue on [GitHub](https://github.com/subutai-io/p2p).

**Comment by jadilet** [comment]
Done in dev
