### ISSUE TITLE
QT QWidgetAction bug on Mac OSes

### ISSUE THREAD

**Issue by btemir** [subutai-io/tray#26]
Custom widget menu action (QWidgetAction) is showed as empty strings on Mac. It's a known  bug on Mac OSes. There should be a way to resolve it.

**Comment by btemir** [comment]
https://forum.qt.io/topic/59534/qwidgetaction-in-menu-not-showing-on-os-x
Changed menu to action. Will see if it will be fixed in 5.6.1.

**Comment by Lezh1k** [comment]
Waiting for qt 5.7 release (15 june 2016).
