### ISSUE TITLE
p2p blocking calls

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/tray#29]
We need non blocking p2p. For example now p2p is blocking application when we call it by 
system("./p2p show") . It should not block our tray application. So need to modify p2p.

**Comment by crioto** [comment]
Note, that some commands, e.g. start requires blocking. 
Basically, you can do the following: remove WaitLock(), Lock() and Unlock() methods from Show() method in instance.go and copy existing Instances map.

**Comment by akarasulu** [comment]
@Lezh1k is this needed to remove the problem of waiting for swarm joining by asynchronously joining swarms?

**Comment by crioto** [comment]
This issue was solved and can be closed
