### ISSUE TITLE
P2P version cannot be fully seen on MacOS 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#296]
![image](https://user-images.githubusercontent.com/17665678/31383946-bd06e766-adde-11e7-9b0e-406608c9da50.png)

**Comment by crioto** [comment]
Use `p2p version -h` instead of `p2p version`

**Comment by Lezh1k** [comment]
It's not only macOS . Should be fixed everywhere.

**Comment by akylbekesenaliev** [comment]
Tested on MacOS -El Captain - success
