### ISSUE TITLE
[Mint182] Deb pkg should check for available terminals

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#301]
Package version 6.0.2 on website fails on Mint Sonya 18.2 because xterm is not installed by default and this is what the Tray uses by default. The default terminal on Sonya is mate-terminal. The Debian package on installation should set the proper terminal to use in settings when installing or have a dependency on xterm to force pulling it down.

Got the following popup notification:

![screenshot at 2017-10-11 03-55-36](https://user-images.githubusercontent.com/10051386/31413298-f5bc85ba-adee-11e7-8ac7-a7a2b5dcd8c8.png)

> ubutai@mint182 ~ $ p2p debug
DEBUG INFO:
Number of gouroutines: 18
Instances information:
Hash: swarm-0f6cd064-1de7-48f4-a231-6822950971e5
ID: 89f69c8d-ae05-11e7-8cec-028073b4e28a
Interface vptp1, HW Addr: 06:21:61:21:0e:e8, IP: 10.16.79.245
Peers:
	--- 35a0ed6c-acf0-11e7-85aa-0ec5f3ffffbf ---
		HWAddr: 06:c5:aa:a3:8d:6b
		IP: 10.16.79.1
		Endpoint: 18.231.3.245:40622
		Peer Address: 96.246.161.207:51131
		Proxy ID: 8
	--- End of 35a0ed6c-acf0-11e7-85aa-0ec5f3ffffbf ---
	--- 602b6ab0-ae05-11e7-841a-028073b4e28a ---
		HWAddr: 06:18:00:16:29:e8
		IP: 10.16.79.2
		Endpoint: 18.231.3.245:40622
		Peer Address: 179.241.204.60:59972
		Proxy ID: 2
	--- End of 602b6ab0-ae05-11e7-841a-028073b4e28a ---

So p2p is working correctly. I looked into the settings of Commands tab and saw the terminal being used was xterm. I tried to invoke an xterm:

> subutai@mint182 ~ $ xterm
The program 'xterm' is currently not installed. You can install it by typing:
sudo apt install xterm

WARNING: If you use mate-terminal make sure the code invokes it with the proper switch to launch the ssh command inside it. The switch might be different from xterm. I tried setting it in settings but it would not work for me.

Additional files:

[error_11.10.2017.txt](https://github.com/subutai-io/tray/files/1373587/error_11.10.2017.txt)
[info_11.10.2017.txt](https://github.com/subutai-io/tray/files/1373588/info_11.10.2017.txt)

**Comment by Lezh1k** [comment]
mate-terminal's arguments are `-x bash -c` . 
adding checks to deb postinst

**Comment by Lezh1k** [comment]
It's better to change tray.

**Comment by jadilet** [comment]
# Xterm
xterm -e "ping 8.8.8.8;bash"

# Gnome Terminal
gnome-terminal -x bash -c "ping 8.8.8.8;bash"

# Terminator
terminator -x bash -c "ping 8.8.8.8;bash"
terminator -e "ping 8.8.8.8;bash"

# Mate Terminal
mate-terminal -x bash -c "ping 8.8.8.8;bash"

# Xfce4 Terminal
xfce4-terminal -x bash -c "ping 8.8.8.8;bash"

# Guake Terminal
guake -e "ping 8.8.8.8;bash"

# Konsole Terminal
konsole -e "ping 8.8.8.8"

# Sakura Terminal
sakura -x "ping 8.8.8.8"
sakura -e "ping 8.8.8.8"

# Termit terminal
termit -e "ping 8.8.8.8"

# Roxterm terminal
roxterm -e "ping 8.8.8.8"

# Rxvt terminal
rxvt -e ping 8.8.8.8

# Kterm Terminal
kterm -e ping 8.8.8.8

# Aterm terminal
aterm -e ping 8.8.8.8

# Evilvte terminal
evilvte -e ping 8.8.8.8

**Comment by Lezh1k** [comment]
Changed in tray.
