### ISSUE TITLE
[Ubuntu] Tray and SSH don't work well

### ISSUE THREAD

**Issue by rschulman** [subutai-io/tray#302]
Problems:
1) The tray is preconfigured to use xterm which is ancient and hard to use.
2) The tray ssh command has a `;bash` appended to the end for some reason, which is causing problems with opening an ssh session in `gnome-terminal`.

**Comment by akarasulu** [comment]
@rschulman thanks for this ... we'll try to get this fixed immediately for the next release.

**Comment by Lezh1k** [comment]
With `gnome-terminal` we need to change terminals argument (in tray settings) to `-x bash -c` . 
;bash appended because sometimes user needs to see if error happened.
