### ISSUE TITLE
Automatically login if remember me was selected and credentials are cached 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#32]
Very low priority improvement.

When restarting the tray always asks to log back in but it has my credentials since I selected remember me. If it does have them why it waits for me to press the login button? Can't it just login without showing the dialog? 

If we do implement this, then we also need a menu item to enable logging out and logging in. One menu item based on state can do both functions. If user is logged in, menu item says 'logout'. If user is logged out, then menu item says 'login'. Pressing login should show the login dialog instead of automatically logging in.

**Comment by Lezh1k** [comment]
Done
