### ISSUE TITLE
Cant update Tray on Windows  8.1

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#326]
![image](https://user-images.githubusercontent.com/17665678/32209582-0fbbc936-be33-11e7-8fec-e3b7ef7551f5.png)
Performed steps: 
- downloaded Tray MSI package from the site 
- branch Dev
- Installed
- launched 
- Tried to Update Tray
Result: ^^^ 

**Info logs:**
[Info.txt](https://github.com/subutai-io/tray/files/1429713/Info.txt)

**Comment by akarasulu** [comment]
Please immediately investigate this problem and let's fix it fast.

**Comment by Lezh1k** [comment]
Run as admin. As we discussed many times : there is permission issue with tray / p2p location on win machines.
