### ISSUE TITLE
Hide tray program in dock when there is no dialog open

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#33]
Very low priority improvement.

The tray icon on all platforms should not be visible in the "dock" if it does not have a dialog window open. Only with a window should it be visible like so:

![screen shot 2016-04-01 at 11 01 18 pm](https://cloud.githubusercontent.com/assets/10051386/14224089/b1aab5ce-f85d-11e5-9d02-e94e571fff1f.png)

**Comment by Lezh1k** [comment]
Just need to add these strings:

<key>LSUIElement</key>
<string>1</string> 

right before </dict>. Need to change Info.plist. Tested and works.
