### ISSUE TITLE
Wrong path to p2p 

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/tray#331]
I installed latest production version of P2P and Tray from subutai.io website, Tray version is 6.1.0,
P2P version was 6.1.9.
In about dialog of tray it showed that updated for p2p is available, when I clicked to "Update" it failed with error: `rename /usr/bin/p2p to /usr/bin/p2p.tmp failed. Permission denied`
In Tray settings path to p2p was `/usr/bin/p2p`, but it have to be `/opt/subutai/bin/p2p`.

**Comment by crioto** [comment]
https://stackoverflow.com/questions/18159662/get-real-path-of-a-symlink
