### ISSUE TITLE
Allow selection of preferred terminal on OS X

### ISSUE THREAD

**Issue by rschulman** [subutai-io/tray#336]
The tray app on OS X does not allow the user to choose which terminal application to use, unlike the Linux tray. It would be nice to be able to specify iTerm instead of the default Terminal.

**Comment by SEFI2** [comment]
@rschulman Thanks for mentioning this issue. We are currently working on it and trying to make choices of terminals in both Linux and Mac more user-friendly. If you have some more recommendations on this issue as OS X user, any ideas are welcome.

**Comment by amol4anoff** [comment]
Fixed.
