### ISSUE TITLE
[Win] Unresponsive tray icon after day of operation

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#34]
This stale unresponsive tray application issue should be considered critical.

Right clicking the tray icon in Windows 7 after it has been operating for a day or two does not show the popup menu. If need be I can gather more information about the process.

**Comment by akarasulu** [comment]
This is happening with the new release and is a really urgent problem that needs to be fixed.

**Comment by Lezh1k** [comment]
Seem's like it fixed by async system calls.
