### ISSUE TITLE
Tray on OSX doesn't respect text box entry

### ISSUE THREAD

**Issue by BenjaminHCCarr** [subutai-io/tray#345]
On macOS/OSX if you type a path into one of the binary text box or copy/paste for example `/usr/local/bin/VBoxManage` into the field, Tray doesn't register or save the changes.

However if you navigate to the binary with the `[...]` button the Tray application records the change and respects it.

**Comment by crioto** [comment]
@BenjaminHCCarr I couldn't reproduce this on MacOS Sierra 10.12.6 with latest (6.2.0) tray. I was playing with path to p2p and it saves hand written path without problems.

**Comment by SEFI2** [comment]
@BenjaminHCCarr Can you paste it by right click->Paste? And if it works then this issue could be because of some minor updates in OS X. I have found out that some MAC users have copy/paste issues for some fields and they overcome the problem by updating.

**Comment by amol4anoff** [comment]
Fixed.
