### ISSUE TITLE
Updated tray no longer launches on Ubuntu

### ISSUE THREAD

**Issue by rschulman** [subutai-io/tray#361]
SubutaiTray all of a sudden no longer starts under Ubuntu 17.10. Error message is as follows:
```
SubutaiTray: error while loading shared libraries: libinput.so.5: cannot open shared object file: No such file or directory
```

**Comment by Lezh1k** [comment]
Yes, this is known issues. We changed build system and new one depends on libinput and some of libxcb* .

**Comment by rschulman** [comment]
@Lezh1k: Do I need to do anything on my end to get it working again?

**Comment by akarasulu** [comment]
@rschulman @Lezh1k will probably have this fixed in the next release. You'll need to just upgrade.

**Comment by amol4anoff** [comment]
Checked on ubuntu17.10, no such error was detected.
