### ISSUE TITLE
Enable users to drag&drop notification dialogs

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#363]
Users should be able to drag notifications on the screen. They need it, to not be disturbed with notifications when they are using the screen part where notifications appear. And also if there are multiple notifications at the same time, then it would be better to read them on one screen by dragging some notification dialogs to other part of the screen.

**Comment by amol4anoff** [comment]
Implemented, but it would be great if you implement ability to drag and drop clicking the whole notification window. For now it is only possible to move, clicking icon of notification. It would be much easier and comfortable.

**Comment by ibragim13** [comment]
@SEFI2 @jadilet Implemented, but it would be great if you implement ability to drag and drop clicking the whole notification window. For now it is only possible to move, clicking icon of notification. It would be much easier and comfortable.

**Comment by SEFI2** [comment]
@amol4anoff @ibragim13 Actually, the whole notification dialog is clickable. But there is the text field (which shows notification messages) on top of the dialog, which is not draggable and which covers most of the dialog. So when users selects text fields, they can't move. Any other part of the dialog is draggable. Currently, I don't know how to deal with it in a clean way and I don't think it would be big problem for users. But yes, we will try to make `drag&drop` better.  I appreciate your feedbacks and would like to get more advises on UI part from you.

**Comment by akarasulu** [comment]
These are a low priority. Do not waste bandwidth on these cosmetic issues until other more critical things are handled. We have installation and update failures.

**Comment by amol4anoff** [comment]
Done.
