### ISSUE TITLE
Show notifications in cascade manner

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#364]
If there are multiple notifications, then users should see them on cascade manner instead of seeing notifications on top of other notifications.

**Comment by SEFI2** [comment]
![image](https://user-images.githubusercontent.com/22672448/32771688-b728daa4-c94d-11e7-8b35-69397ea4674c.png)
[DRAFT SOLUTION]

**Comment by amol4anoff** [comment]
Checked. Fixed

**Comment by ibragim13** [comment]
Fixed in Prod.
