### ISSUE TITLE
Need to show list of terminals that exists in Linux and OS X

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#367]

**Comment by jadilet** [comment]
It would be better to show existing terminal in completion. Instead of showing all existing terminals in a lists.

![available terminal](https://user-images.githubusercontent.com/6593519/33062129-6618dd82-cec8-11e7-9445-28935510c0a8.png)

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Done.
