### ISSUE TITLE
Add proper changelog

### ISSUE THREAD

**Issue by crioto** [subutai-io/tray#376]
Tray doesn't have root changelog file, but it uses one for debian package. We need to start using root CHANGELOG file and generate changelog in debian format during tray packaging. 
You can take CHANGELOG from p2p as an example: https://github.com/subutai-io/p2p/blob/master/CHANGELOG
Changelog converter to debian format is also exists in p2p inside a configure script: https://github.com/subutai-io/p2p/blob/master/configure
Example of proper debian changelog is here: https://github.com/subutai-io/tray/blob/master/deb-packages/deb-packages-internal/debian/changelog

**Comment by Lezh1k** [comment]
Please add changelog to changelog.md too . 
Doxygen uses that file.

**Comment by amol4anoff** [comment]
Fixed.
