### ISSUE TITLE
SSH.exe and ssh-keygen.exe seem to be missing in required directory

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#379]
I went to settings -> commands, there're 4 fields, I specified paths for P2P command and others. When pressing OK button, it shows that there're 2 incorrect paths. When i check directories, it seems that ssh.exe and ssh-keygen.exe files are missing in required directories.
![tray-p2p](https://user-images.githubusercontent.com/33647491/33063076-97beeb80-cecb-11e7-915e-a29c03f57150.png)

**Comment by ibragim13** [comment]
Fixed in Prod.
