### ISSUE TITLE
Peer Informations

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#380]
So now users don't have clear information about their Peers (who is using their Peer, etc). Currently user gets notification when some other user uses his/her Peer. But this information only goes to notification history. I recommend to pop up a dialog (similar to Environment info), when User clicks one of his Peers, where he can see more info, also start/stop Peer and go to SS console of this Peer.  

REFERENCE ISSUES:
https://github.com/subutai-io/tray/issues/165
https://github.com/subutai-io/tray/issues/167
https://github.com/subutai-io/tray/issues/98

DEMO VERSION:
![image](https://user-images.githubusercontent.com/22672448/33279723-d0cce348-d3c9-11e7-916d-8a24c9ef3ab5.png)

**Comment by amol4anoff** [comment]
Implemented.
