### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#381]
Some recommendations:
1. Add `Updates` menu and merge to that menu current `About` menu and `Settings->Updating` menu
2. Seems like user will not mostly need to change and create SSH-keys. So the `Settings` menu will be good place for `SSH-Keys Management` menu
3. Move `Launch->Hub` to main menu

**Comment by SEFI2** [comment]
Moved `SSH-Keys Management` under `Settings` menu. Remove Launch Menu, instead added `My Peers` menu for launching each peer.

**Comment by amol4anoff** [comment]
Done.
