### ISSUE TITLE
EZ-Desktop with Subutai Tray 

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/tray#387]
EZ-Desktop with Subutai Tray
Subutai users can have desktop applications running on Subutai containers. For this users, we need to implement the easy desktop feature. EZ-Desktop is a remote desktop solution provided by Subutai Tray, where users can easily get access into the graphical user interface of desktop applications running on Subutai containers.

* By default install X2Go client to client's machine
* If any supported Desktop interfaces run inside Subutai containers, Tray will enable Ez-Desktop button, which will launch X2Go client with ready parameters (IP address, SSH key)

**Comment by zubaidullo** [comment]
currently issues what I see: 
1) Install x2go client default with Tray
2) Provide API for E2E plugin
3) Add EZ-Desktop button (if desktop env. exists inside container)
4) Show configs when user click to EZ-Desktop button
- IP address (or domain)
- port
- etc.

**Comment by amol4anoff** [comment]
Ez-Desktop works on master.
