### ISSUE TITLE
Environments disappear, when user logouts and logins back

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#388]
REPRODUCTION:
1. Run Tray
2. See Environments
3. Logout (do not close tray)
4. Login
5. See Environments (environments menu is empty)

**Comment by amol4anoff** [comment]
Fixed

**Comment by amol4anoff** [comment]
Fixed.

**Comment by SEFI2** [comment]
Still have this problem

**Comment by amol4anoff** [comment]
Fixed.
