### ISSUE TITLE
Log files in /opt/subutai/bin

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/tray#412]
I am actually not sure if this should go here or in p2p, but writing log files in /opt/subutai/bin is not really the right place.  From a system admin pov stuff like that should go in /var/log or possibly /var/lib/subutai....  No run-time generated files should ever go to /opt.

**Comment by akarasulu** [comment]
I've been asking for this a long time. Now that Oleg is gone I think the boyz can handle it.

**Comment by akarasulu** [comment]
The tray is a UI application on the desktop. It runs under the logged in user's account. Unlike daemons which run system-wide and log to a log file under /var/log or to syslog.  So using the default mechanisms associated with the UNIX file system layout is not applicable.

Instead, the tray application needs to create a hidden (starting with a dot '.') directory under the user's home directory like `$HOME/.subutai_tray`. Then inside this application directory for the user, the configuration may be stored along with log files and anything else pertaining to the tray.

**Comment by lbthomsen** [comment]
Well, it can if you set the permissions like this:

`lth@ncpws04:/opt/subutai/Libs$ ls -ls /opt/subutai/
total 16
4 drwxrwxrwx 2 root root 4096 Dec  6 00:13 bin
4 drwxr-xr-x 2 root root 4096 Nov  9 10:24 lib
4 drwxr-xr-x 2 root root 4096 Nov  9 10:24 Libs
4 drwxrwxrwx 2 root root 4096 Nov  9 10:24 log`

I'd say when distributed as .deb files /opt is also a mistake.  Binaries should go as follows:

/usr/bin/SubutaiTray

p2p's location depends on "who" is executing it.  If superuser/root only it belongs in /sbin or /usr/sbin, if executed by SubutayTray then I'd say /usr/bin as well.

For user executed stuff only TWO locations are acceptable for writing: 

1. $HOME/.subutai 

2. /tmp/.subutai

Distinctions should be made - $HOME/.subutai for stuff that need to survive reboots, temporary disposable stuff in /tmp.  Assume NO write access to /opt, /var, /bin etc. 

Since p2p is running as a daemon I'd say it would be acceptable for that to use syslog with some well defined facility.

As for SubutaiTray I'd say log to stderr.  If you want to see the log execute it in terminal or the user can redirect to whereever he want.

**Comment by amol4anoff** [comment]
Fixed.
