### ISSUE TITLE
Wrong notifications about Peers 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#416]
Peer Notification system works as following:
1. If new Peer is in REST API, which is not in temporary list of Peers, then add to to temporary list of Peers and show notification that Peer is connected.
2. If a Peer is not in REST API and is in temporary list of Peers, then delete from temporary list of Peers and show notification that Peer is disconnected.
Same commands for Environments of your Peer.

The logic is true, but there is interesting case:
When user deletes the UNHEALTHY Environment,  then it goes UNDER DEVELOPMENT. And it shows that new environment was connected to user's Peer.

The reason:
Hub doesn't send `UNHEALTHY ENVIRONMENTs`.

**Comment by amol4anoff** [comment]
Fixed.
