### ISSUE TITLE
Production Tray does not install 6.3.0 as expected by 6.2.0

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#418]
### System
macOS Sierra

### Preparations
Uninstalled previous dev tray to install production tray of version 6.3.0. Also I installed the latest production p2p version of 6.2.5 before hand. Fresh reboot.

### After Installation

Right after installing the tray started immediately. It was the old version 6.2.0. I was expecting 6.3.0. So I went to the About thingy and updated it. 6.3.0 was installed.

**Comment by amol4anoff** [comment]
Fixed.
