### ISSUE TITLE
Tray SSH key generation dialog needs to use correct titles

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#419]
General rule use first character capitalization in all labels.

1. In menu, and the dialog title needs to be `SSK Key Manager` instead of `SSH key generation`
2. `Save changes` button on bottom right hand side should be `Deploy Key[s]`
3. `Select all` checkbox should be `Select All to Deploy`
4. `Ssh-keys :` should be `Existing Keys:` without a space between the colon and last 's' at end of Keys
5. `Healthy environments :` should be `Healthy Environments:` again no space

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Corrected.
