### ISSUE TITLE
Can't update my p2p

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#422]
I go to tray -> about to update p2p, when push update button, it shows - error message, saying it's failed to update.
![ssherror](https://user-images.githubusercontent.com/33647491/33512600-50b31458-d6e8-11e7-9e2a-eac6cf253bf7.png)

**Comment by akarasulu** [comment]
Very high priority!

**Comment by amol4anoff** [comment]
Fixed

**Comment by amol4anoff** [comment]
Fixed.
