### ISSUE TITLE
Would be cool to enlarge small ssh button in tray

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#423]
Now we have very small ssh button in tray (access environments section). It's very small, bad eye-sight dudes will not recognize it.
![smallssh](https://user-images.githubusercontent.com/33647491/33512649-2a3c77fa-d6e9-11e7-83dc-66af26433c9f.png)

**Comment by akarasulu** [comment]
I had commented on this f2f while talking to you 3-4 days ago if you remember.

**Comment by amol4anoff** [comment]
Still the same on master...

**Comment by amol4anoff** [comment]
OK, now its bigger.

**Comment by amol4anoff** [comment]
Fixed.
