### ISSUE TITLE
Establish SSH connection with every container after successfull join to swarm

### ISSUE THREAD

**Issue by crioto** [subutai-io/tray#426]
After we found that p2p connection established we want to establish SSH connection to every containers inside a swarm. If SSH connection receives handshake from SSH server we need to disconnect from it right away and enable container menu item in tray. If SSH connection didn't respond we will keep container menu item disabled. 
Also, we need to run this process periodically to see if container is still connectable or not. Time value for this period needs to be configurable.

**Comment by akarasulu** [comment]
Might be nice to collect the errors and allow the user to report them to us. Perhaps this is another issue all together.

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Fixed.
