### ISSUE TITLE
P2P Swarm interaction refactoring

### ISSUE THREAD

**Issue by crioto** [subutai-io/tray#428]
Currently we connect to a p2p swarm only when user clicks on EZSSH button. We need to modify this behavior to provide better user experience, reduce connection time and highlight p2p swarm problems on user side.

**Comment by amol4anoff** [comment]
Connection time is still not reduced.

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Fixed.
