### ISSUE TITLE
Tray shows two environments of the same name in "Peer notifications" 

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#430]
![image](https://user-images.githubusercontent.com/22672448/33538452-a00f3c34-d8eb-11e7-962e-d4b12f805e25.png)

**Comment by SEFI2** [comment]
It will no longer show environments of Peers as Notification, instead it will show envs for each Peer on Dialogs.

**Comment by amol4anoff** [comment]
New feature is implemented.
