### ISSUE TITLE
Show popup windows in tray above browser window

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#436]
As user i want to see popup notifications before my browser window if the window is opened. Right now all tray popup notifications are shown under browser.
Like this:
![selection_003](https://user-images.githubusercontent.com/33647491/33590165-dd7f8f9e-d9a7-11e7-9dea-a4136f15d0ac.png)

**Comment by SEFI2** [comment]
@amol4anoff Good Point, thanks. Can I know your OS? I also have faced this problem, but mainly on Windows machine. And didn't give importance thinking it is only happening with my machine.

**Comment by akarasulu** [comment]
This is cosmetic but a higher cosmetic issue. Once critical issues are handled this could be the first cosmetic problem to confront.

**Comment by SEFI2** [comment]
Found out that it has straightforward and one-line. Here : `dlg->setWindowFlags(dlg->windowFlags() | Qt::WindowStaysOnTopHint);`

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Shows properly.
