### ISSUE TITLE
Don't have logs in notification history. Mac High Sierra

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#446]
I run tray 6.3 on Mac, then have some errors (will specify in p2p). And when i go to notification history menu, it is empty! Please have a look.
<img width="821" alt="tray" src="https://user-images.githubusercontent.com/33647491/33754319-dbb2a352-dc15-11e7-9002-706cbb8162d3.png">

**Comment by amol4anoff** [comment]
I changed directory path for logs in settings, and then logs appeared. Can there be path issue?

**Comment by SEFI2** [comment]
@amol4anoff Most probably one of two things happened here: 
1. Wrong path to logs storage
2. You current user don't have enough privilege to create files at specified path.

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Now have.
