### ISSUE TITLE
Strange crash when environments are modified, while dialog is openned

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#469]
Reproduce:
   1. Open Tray (6.3.0 master or dev)
   2. Open all of the environment dialogs.
   3. Open SSH-Key Management
   4. if there is no key for env, then add, if there is then remove key. 
   5. Press deploy key button
   6. Wait couple of minutes

Step 4 is needed to modify environments, but you can use any other way to modify the environments (for example, delete one of your environments from hub).

**Comment by amol4anoff** [comment]
Fixed
