### ISSUE TITLE
[Master Tray] p2p show is giving more amount of environments then it is actually on Hub.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/tray#521]
On masterhub I have only 4 environments.
![screen shot 2018-01-04 at 21 12 54](https://user-images.githubusercontent.com/31571523/34569850-39ed42f4-f194-11e7-8c80-ef9159ba4746.png)

But p2p show is showing 10 environments

Last login: Thu Jan  4 21:09:20 on ttys000
-bash: nexport: command not found
Shahris-MacBook-Air:~ shahrizadakarasulu$ p2p show
	06:7b:e6:b5:dc:ec	10.152.99.248	swarm-a8caf333-41c0-4221-bd3e-648cbd2db37d
	06:eb:c6:00:11:85	10.141.6.245	swarm-f84da41c-e03d-4825-92ae-e4671bbf7546
	06:da:84:a8:79:cc	10.210.122.245	swarm-fba12863-c59a-4197-be91-6b7d59c8f51b
	06:a1:e2:3b:a4:f8	10.144.229.245	swarm-b9116064-ff80-4ac8-bdff-54d5fd69a155
	06:37:c5:67:50:3b	10.123.68.247	swarm-9d0b8419-75a1-4826-b8b0-ff67e4500fd8
	06:2f:8f:0c:e5:25	10.224.204.246	swarm-48cf2715-bd19-4692-9d05-2a43d61997bf
	06:81:f0:57:6c:9b	10.159.113.245	swarm-1f84947e-c991-45af-9c2c-179e2f23bbbf
	06:55:83:4b:f1:e3	10.86.235.245	swarm-1b160d57-656c-4700-8891-86225e38f0a5
	06:9e:ea:39:2d:5d	10.209.245.245	swarm-18d66038-d66b-4ce4-bcba-e48166edeb4f
	06:61:2e:6f:17:69	10.102.158.245	swarm-90239a6a-feca-451a-a981-928bf2e77136

Shahris-MacBook-Air:~ shahrizadakarasulu$ 

[logs_2018.01.04.txt](https://github.com/subutai-io/tray/files/1603710/logs_2018.01.04.txt)

**Comment by jadilet** [comment]
This issue already implemented by this issue https://github.com/subutai-io/tray/issues/495.

**Comment by amol4anoff** [comment]
Fixed

**Comment by amol4anoff** [comment]
Fixed.
