### ISSUE TITLE
Weird menu behavior on environment being modified

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#53]
I looks like environments under modification in the Hub are being returned but they do not have some things setup so we're seeing this weird behavior. Let's also get state information from the Hub when we get the JSON and display state graphically in the environment's menu item for the different states. This way the user will see that he cannot access various things and will get a hint as to what is happening instead of things things are not working.

![screen shot 2016-05-18 at 11 29 38 pm](https://cloud.githubusercontent.com/assets/10051386/15381758/8604f980-1d50-11e6-867f-991e51507e43.png)

**Comment by Lezh1k** [comment]
Need more details about how to reproduce

**Comment by Lezh1k** [comment]
Added synchronizations and many things. Tested many times. Can't reproduce. Will reopen if this bug appears.
