### ISSUE TITLE
Make state signs for environments in tray

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#530]
As a user i wanna see environments' state signs to be able to easily recognize what's going on with my environment.
Green sign - healthy, red - unhealthy, yellow - under modification.

![tray1](https://user-images.githubusercontent.com/33647491/34810568-7067a66c-f6c6-11e7-99da-ed2ee78824d8.jpg)

**Comment by akarasulu** [comment]
Awesome request!!
