### ISSUE TITLE
Tray broken dependencies on Ubuntu 17.04

### ISSUE THREAD

**Issue by liquuid** [subutai-io/tray#531]
Hi, yesterday I upgraded my Tray version and it does'nt work anymore: 

`SubutaiTray: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory`

So, I've created symlinks point missing lib to new one installed on my machine and this happened: 

`SubutaiTray: symbol lookup error: SubutaiTray: undefined symbol: ucnv_getDefaultName_52`

**Comment by SEFI2** [comment]
@liquuid  There were some additional libraries added to last releases. So when you just update the tray from tray itself, it will only replace the binary file (SubutaiTray) and will not update libraries.  So instead try to just install from the debian package, which you can get from https://subutai.io/install/index.html

**Comment by liquuid** [comment]
Did worked, thanks.

**Comment by akarasulu** [comment]
These are all signs of not properly using the right directives in the Debian Package Manager's control file. @SEFI2 please make it your objective to thoroughly learn, understand and use these directives so users do not have these problems. Ask for help from @happyaron. He's got a good understand of these things.
