### ISSUE TITLE
When i delete Tray from Mint, it remains some leftovers

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/tray#544]
After you delete Subutai Tray from Linux Mint, remnants of it are present in menu section, please fix this.

**Comment by SEFI2** [comment]
The solution wasn't deployed to prod yet. It is deleting perfectly on master

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
If we face this again, will re-open.
