### ISSUE TITLE
Network forwarding doesn't work.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#56]
For replay this bug you need:

Test case
Step preparation: should install SS win installer.
1) Run SS through tray -> change wifi network -> relaunch the SS launcher.

Result: you get an Error
![upload - sf webmaster](https://cloud.githubusercontent.com/assets/11311924/15777340/3ce6dff4-29b0-11e6-9364-534f97019e3d.jpg)
 
[error_03.06.2016.txt](https://github.com/subutai-io/tray/files/297464/error_03.06.2016.txt)
[info_03.06.2016.txt](https://github.com/subutai-io/tray/files/297463/info_03.06.2016.txt)

**Comment by Lezh1k** [comment]
Fixed
