### ISSUE TITLE
Do network forwarding by reloading the page.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#57]
Right now when I change wifi connection I should reload the SS loader. 

Improvement: do network forwarding by reloading the page by clicking F5, it will be more user friendly.

**Comment by Dilshat** [comment]
e2e plugin can send QUERY request to tray to get actual IP, then it can check that SS page is open in a tab, and check its IP, in case it is old it can refresh the tab.
@TalasZh wdyt?

**Comment by TalasZh** [comment]
sure e2e-plugin is capable to track user actions within browser and send queries to tray, as we already do with web-sockets for EZ-SSH.
Probably best way to do it  to add `Reload SS Loader` button to extension toolbar panel. 

![screen shot 2016-06-04 at 11 43 20](https://cloud.githubusercontent.com/assets/3873442/15798681/d999ccb4-2a62-11e6-8683-5dc2276c0fed.png)

New button, as I understood from above, will send query to tray and reload current page with updated IP, right? @Dilshat

**Comment by Dilshat** [comment]
@TalasZh not even a button, rather a background thread, if a corresponding (new) settings is enabled in Options, say **Update IP automtically**

**Comment by TalasZh** [comment]
al-right, the only thing that is needed when to send queries to tray? e2e-plugin cannot detect wifi/network changes

**Comment by Dilshat** [comment]
Right @TalasZh , Plugin works with Tray app, Tray app can detect network changes, @Lezh1k wdyt?

**Comment by Lezh1k** [comment]
We don't need track network changes. Once user press F5 we need to send query to tray and receive actual IP .

**Comment by Dilshat** [comment]
so we can get actual IP from tray @TalasZh
