### ISSUE TITLE
States of Environments in tray differ from hub's states

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#574]
Tray stopped to request from hub, suddenly after losing the connection for sometime

**Comment by SEFI2** [comment]
`Reason`:
When internet disappears or hub is down, tray tries to reconnect but stuck at some point. And it causes environments stay same, even they were deleted or new environments were added from hub website. 

`Solution`:
Implemented a timer, which waits 30 seconds for reconnection and if it didn't connect, then it closes the connection and starts the new one.

`Reproduce`:
* Login 
* Wait couple of minutes, while connection is well established
* Turn off the wifi (or internet connection)
* Add new envs or delete some envs
* Wait for some time 2-3 minutes (more is better) 
* And connect to wifi
* Make sure internet is connected
* Wait for some time 20-50 seconds
* See if `env` list was modified or still the same.

**Comment by amol4anoff** [comment]
@kadyr how can i add environment if my internet is off???

**Comment by SEFI2** [comment]
@amol4anoff from another laptop

**Comment by amol4anoff** [comment]
Will now test it.

**Comment by amol4anoff** [comment]
Didn't face this error.

**Comment by amol4anoff** [comment]
No such error in prod.
