### ISSUE TITLE
Show the state of p2p in tray

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/tray#577]
States:
  * Running
  * Not Running 
  * Cannot find p2p

**Comment by amol4anoff** [comment]
What i see:

-P2P is running
-P2P is loading
-Can't launch P2P

**Comment by amol4anoff** [comment]
@Erkin97

**Comment by SEFI2** [comment]
@amol4anoff p2p is not running will be show, when you stop the p2p daemon

**Comment by amol4anoff** [comment]
OK

**Comment by amol4anoff** [comment]
Works in prod
