### ISSUE TITLE
Adding generated SSH key to environment should be automated

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#59]
We should automate this:

![image](https://cloud.githubusercontent.com/assets/7465404/15825175/8212ecbe-2c24-11e6-8dd8-5c3d0f611b1c.png)

And we can do this easily with Hub: should be matter of single REST call.

**Comment by Lezh1k** [comment]
Test scenario: 
1. Launch tray
2. Go to "Generate ssh key" dialog.
3. If you have public key it will be displayed and you can skip this step. Else press "Generate" key. 
4. If everything is fine you will see new generated key in main text area. 
5. Press button "Add ssh key to environments". 
6. Message about successful completion should appear. If not - error should be displayed and logged into error log file.
7. If tray displays success need to check result. First on SS Console page. Run SS console from  tray or use another way to launch it. 
8. There is ssh-key list in "environments" page. You should see new key.

**Comment by NikolaiB** [comment]
How about implementation fuction of 'auto close' window with key after button 'Add key to Environments' been pushed? For more amicability may be with some fading effect.
![30-08-2016 11-56-44](https://cloud.githubusercontent.com/assets/11311924/18077681/81440992-6eb1-11e6-960f-4af6dde2256b.jpg)

**Comment by zubaidullo** [comment]
We need to test Hub and Tray side.  Hub side is implemented, please test main functionality first (if there is any problems, I will refactor), SSH Keys should be added to containers via Hub. 
Then, improving UI can be done easly.

**Comment by NikolaiB** [comment]
I tested, SSH keys add normally.
