### ISSUE TITLE
[Mac OS] SSH to containers on remote peer doesn't work

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#60]
I installed dev version of Mac Net Installer:

![image](https://cloud.githubusercontent.com/assets/7465404/15855478/7bf1738e-2cd1-11e6-91e3-6051583b3feb.png)

Created a new environment container from three peers: my local peer and two other remote ones. 

Tray opens SSH successfully to container on my local peer only. For containers on remote peers it gives always this error:

![image](https://cloud.githubusercontent.com/assets/7465404/15855552/ecd5acc8-2cd1-11e6-9fab-0c0d6619eb6c.png)

May it be related to this issue? https://github.com/subutai-io/subos/issues/364

**Comment by Dilshat** [comment]
@asanaliev please retest and close if ifxed

**Comment by asanaliev** [comment]
Now it looks more stable and smoother. Good job!
