### ISSUE TITLE
[Tray Error message] Should change the error to readable text that VM is not started, please start VM at first.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#62]
You can also add the way how to start it: Tray -> Virtual Machines -> Play
![pasted image at 2016_06_08 09_45 pm](https://cloud.githubusercontent.com/assets/11311924/15900946/1df5b84c-2dc3-11e6-988b-8716ed454c94.png)

**Comment by Lezh1k** [comment]
Not only turned off machine leads to this error. It could be network error, old virtualbox or something else. We have these error codes and messages and can explain what is going on .
