### ISSUE TITLE
[Win 7] Can't open SS Console

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#63]
I installed on Windows 7 Ru. (See details: https://github.com/subutai-io/installers/issues/47). But failed to open the SS Console. 

![image](https://cloud.githubusercontent.com/assets/7465404/15986858/e5d553e4-3035-11e6-8596-a89abcffcb45.png)

After some delay (~20 sec) I am getting this:

![image](https://cloud.githubusercontent.com/assets/7465404/15986859/f23ba926-3035-11e6-99ba-33ab97677e9c.png)

I restarted subutai vm instance twice and checked again. Same result. 

Network settings:

![image](https://cloud.githubusercontent.com/assets/7465404/15986873/3716993e-3036-11e6-9624-b5d203484669.png)

![image](https://cloud.githubusercontent.com/assets/7465404/15986874/396de426-3036-11e6-9d5c-a00a033ccbaf.png)

Both of ping and telnet 8443 to 10.0.2.15 don't work. 

Please let me know should I attach any logs or config files. Also we can organize TeamViewer session for remote debug.

**Comment by btemir** [comment]
yes, need karaf logs, ifconfig from RH

**Comment by asanaliev** [comment]
[2016-06-12_install_log.txt](https://github.com/subutai-io/tray/files/310441/2016-06-12_install_log.txt)

I checked RH: there is no management. I will reinstall and check again.

**Comment by asanaliev** [comment]
Yes, after reinstalling I could open the SS console successfully and register a peer to Hub. 

We have to make the tray check if management is installed. For example, using some REST endpoint. 
Otherwise, some new users will get same situation and be confused.
