### ISSUE TITLE
Check if management is installed before launching the SS Console

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/tray#64]
Some users will be confused, especially new ones, if they get `can't open web site` when open SS Console. A reason may be simple: management is not installed. See for example: [[Win 7] Can't open SS Console](https://github.com/subutai-io/tray/issues/63)

Would be more user-friendly if Tray checks ports and if management is installed by requesting some REST API. And show some page (or dialog) with explanation. Example, 
> The management container is not installed. Please login to RH and run `sudo subutai import management`. Then check again.

**Comment by Lezh1k** [comment]
"some REST API" - tray works with HUB API. Need to implement this on HUB.

**Comment by asanaliev** [comment]
Hub API is needed when Tray interacts with Hub. I think, here Tray should request SS, not Hub. 

For example, management is installed but this peer is not registered Hub. Also Hub doesn't know anything about internal IP address of local peer: 10.0.2.15. But Tray redirects to that IP when we choose "Launch SS Console".

**Comment by Lezh1k** [comment]
Tray receives that IP from RH via ssh and special command. Ok, maybe we can check ports, for example.

**Comment by Lezh1k** [comment]
Done. We use REST call to https://rh_ip:8443/rest/v1/peer/ready
