### ISSUE TITLE
Can not ssh into remote container

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/tray#65]
I created x-peer env and can ssh into containers from SS UI via tunnels (though it takes ~15 sec to ssh into a remote container): 

![image](https://cloud.githubusercontent.com/assets/3367326/16157185/4eebf192-34d9-11e6-99d9-073fdbcc4f59.png)

But from Tray I can ssh only to a local container, and can not ssh into a container on a remote peer:

![image](https://cloud.githubusercontent.com/assets/3367326/16157210/71dc8e28-34d9-11e6-99d4-35371213d4fd.png)

**Comment by akarasulu** [comment]
Is this not more of a port mapping issue @soffokl @tzununbekov ?

**Comment by soffokl** [comment]
Easiest way to check if it is p2p issue or problem on another layer just try to ping remote p2p IP.
@Dilshat can you get this information from your installation?

**Comment by Lezh1k** [comment]
Error 2 means SHELL ERROR. Need to check settings and path to p2p

**Comment by Dilshat** [comment]
@soffokl ping worked, p2p works, this is tray related

**Comment by Dilshat** [comment]
Last version (Of Jun 19) solved the problem

**Comment by Dilshat** [comment]
Seems this problem is not related with remote and local containers,
Specifically i can not ssh to a container on one of peers (subutai.knu.kg)
@Lezh1k i can provide access credentials if needed to see why it happens.
ping between containers work, so p2p works.

**Comment by Lezh1k** [comment]
Need more details. Which errors do you receive etc

**Comment by asanaliev** [comment]
May be related to: [Ping works always, but SSH does not](https://github.com/subutai-io/p2p/issues/153)

**Comment by Dilshat** [comment]
Fixed with last p2p update
