### ISSUE TITLE
[Tray Error message] Get not readable Error message when tray doesn't have access to the internet.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#68]
Run tray, then go to airplane mode.

Result: in a few minutes you will get not readable error message. 
Improvement: change this message to more readable. Something like: 'SS can not connect to the internet. Please check your internet connection.'
![can not connect](https://cloud.githubusercontent.com/assets/11311924/16370574/ace228d0-3c62-11e6-8735-424589277054.jpg)

**Comment by Lezh1k** [comment]
Done.
