### ISSUE TITLE
[RH] Need change "Can't get RH IP address" on "Waiting to start VM"

### ISSUE THREAD

**Issue by NickolaiVarin** [subutai-io/tray#70]
Install SS on Windows 7 -> stop VM -> quit from SS -> start SS -> Start VM -> try to launch to SS console. 
Observe message "Can't get RH IP address". It will be better if message will looks like "Starting VM plase wait."

![exitcode8](https://cloud.githubusercontent.com/assets/16968797/16511960/a083a478-3f6f-11e6-8095-0c2dbe02c0cb.png)

**Comment by Lezh1k** [comment]
Many reasons lead to session_handshake error. So it will be better to use this message. Then user will report to support and support will look at log file for collecting info about the reason.
