### ISSUE TITLE
Questions regarding SSH key generation functionality of tray across platforms.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#76]
@Lezh1k 

Does the tray have the ability to create an SSH key pair on all platforms (win, linux, mac) ?

Does the tray check to see if there's no SSH key before creating one?

Does the tray default to generating an RSA key pair?

Does the tray place the generated key in a standard (expected) location on the platform? Could you please list the locations for each platform for review>

**Comment by Lezh1k** [comment]
1. Yes. (ssh-keygen should be presented)
2. Yes.
3. Yes. 
4. Location of ssh-keys is configurable. Default location is home_folder\.subutai\.ssh (or home_folder\subutai\ssh for windows).

**Comment by akarasulu** [comment]
@btemir you in sync with @Lezh1k on this?

**Comment by Lezh1k** [comment]
Yes, next update everything will be synchronized
