### ISSUE TITLE
Do we show a notifications on the desktop when someone uses your peer? 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#77]
@Lezh1k Have you implemented the code to give users a notification when their peers (on the current desktop machine or elsewhere) start to be used by others? 

Also are we getting notifications on balance changes?

**Comment by akarasulu** [comment]
Don't know if you @samsonbek implemented the nice notifications on the Hub but we need users to also be notified of balance changes and their peers being used by others. We need the same notification in SS (but only for that peer) in the notification area. The notification of others using the peer in SS should be visible to the administrators and the owner of the peer.

**Comment by akarasulu** [comment]
@samsonbek @eabyshev if these features do not exist let's create issues for their respective issue trackers.

**Comment by Lezh1k** [comment]
No, this feature should be first implemented on HUB . Then tray will be able to use it.
