### ISSUE TITLE
Restart services and components after update automatically

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/tray#80]
After update p2p (for example) user receives message "Restart p2p daemon, please". We need to restart it by tray.

**Comment by Lezh1k** [comment]
Test scenario : 
1. If update of p2p is available - press update button in tray->about dialog.
2. After successful update finish receive notification that p2p was updated on Mac OSX and windows. On linux machines you will receive notification about that and will need to restart p2p daemon manually because of many different ways on different linux platforms.

**Comment by akarasulu** [comment]
We need to do with with @crioto suggested approach:

What if you implement it that way, @lezh1k :
1. See if systemd is available and running
2. See if p2p unit exists 
3. Perform actions
4. Do nothing if not


[3:28] 
You will cover around 80% of linux

**Comment by Lezh1k** [comment]
Using systemd requires root privileges. Do we need to add gksudo dependency ?
