### ISSUE TITLE
A Timeout message appears every time new Subutai installed 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#81]
![image](https://cloud.githubusercontent.com/assets/17665678/17578931/074bbe6e-5fb1-11e6-9061-9619d3a00de9.png)
This message appears every  first login time, when I try to login for the first time with a fresh installed Subutai. 
At first I thought this is because of my Networks but then it kept appearing every time I installed a fresh Subutai.

**Comment by Lezh1k** [comment]
Attach error log, please

**Comment by akylbekesenaliev** [comment]
[error_11.08.2016.txt](https://github.com/subutai-io/tray/files/412552/error_11.08.2016.txt)
@Lezh1k

**Comment by Lezh1k** [comment]
Can't reproduce. It's reported that mistake disappeared.
