### ISSUE TITLE
[mac] cannot use ssh-keys storage path with '~'

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/tray#82]
if i trying set path to:
`~/.ssh/subutai-tray` got - You don't have write permission to this folder
but full path (e.g. `/Users/p1gmale0n/.ssh/subutai-tray`) woks

**Comment by Lezh1k** [comment]
It's ok. 
~ -  value of $HOME in bash. But in other applications it is not. So do we need replace ~ with home_folder ? We have standard home path in qt :)

**Comment by p1gmale0n** [comment]
maybe just add hint? like

> You don't have write permission to this folder.
> (Please use full path to directory)

**Comment by Lezh1k** [comment]
It's easier to replace ~ with $HOME actual value

**Comment by Lezh1k** [comment]
Done
