### ISSUE TITLE
[Mint][MATE] Default configuration without bridge bombs

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#830]
Without a bridge available and no bridge selected the create button is still enabled. User can press it and the build will bomb out. It tries to build and even creates a peer entry in the menu but it is not operation. Need to prevent users from creating unless all parameters are correct. So this allowed me to create a peer but it bombed:

![screen shot 2018-04-11 at 8 19 33 pm](https://user-images.githubusercontent.com/10051386/38622740-a9ecb18e-3dc5-11e8-87d1-a3c05e3b01de.png)

Here's the error message in notifications:

```
Peer test-defaults finished to up with errors: [0;31mThere was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: /opt/subutai/Libs/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
[0m
```

Guess this is different from what I expected. As you can see the vm here.

![screen shot 2018-04-11 at 8 19 50 pm](https://user-images.githubusercontent.com/10051386/38622758-b5202004-3dc5-11e8-874e-c8d103e9318c.png)

**Comment by Erkin97** [comment]
* reason is libssl1.0.0 lib was statically built to CC, which is too old 
* Note, need to reinstall CC, or use this command ```sudo rm /opt/subutai/Libs/libssl.so.1.0.0```

**Comment by AlinaPenkina** [comment]
Fixed on master.
