### ISSUE TITLE
Rework Peers menu

### ISSUE THREAD

**Issue by Erkin97-zz** [subutai-io/tray#854]
* Make peer menu dynamic
* Old method: clear peer menu and create new buttons
* New method: update existing buttons
* Pros:
  * No blinks each refresh
  * Easy to fix and modify
  * Less errors and bugs
  * Memory efficient
* Cons:
  * New bugs might emerge, but easy to fix

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by TerGunter** [comment]
Fixed on prod
