### ISSUE TITLE
Add an option to autostart VM after OS reboot

### ISSUE THREAD

**Issue by btemir** [subutai-io/tray#92]
In some cases (on servers for example) VM should be started automatically after OS reboot, in some cases - not(on notebooks having low resources). User should have possibility to set up VM's behavior after OS reboot.

**Comment by NikolaiB** [comment]
The best way is to add to installer option to auto start VM with note about resources (server, low resource machine or high resource machine).
And duplicate this option to preferences in Tray.

**Comment by Lezh1k** [comment]
Should tray application autostart too?

**Comment by NikolaiB** [comment]
Should we add an option to ask used about this during the installation process?
