### ISSUE TITLE
P2P noticed about update but it isn't active in menu "About"

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/tray#93]
In tray of Windows notification message appears without any actions from side of user. But in menu Tray - About 'update button' not active.
Period of appearance set in Tray - Settings - Updating - P2P check for update frequency
![16-08-2016 13-16-13](https://cloud.githubusercontent.com/assets/11311924/17695782/55865dce-63d4-11e6-8d63-17da33f0a554.jpg)
![16-08-2016 13-17-28](https://cloud.githubusercontent.com/assets/11311924/17695789/5c5e97a6-63d4-11e6-938a-6f1d6276a3b1.jpg)
![16-08-2016 13-33-03](https://cloud.githubusercontent.com/assets/11311924/17695800/6aa2a9ba-63d4-11e6-917f-a72c3ea9413d.jpg)

**Comment by Lezh1k** [comment]
Synchronization issue fixed.
