### ISSUE TITLE
Real time monitoring system (RTM)

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/tray#94]
We want great monitoring system. User should be able see state of his environments, containers, processes, traffic, cpu and memory consumption and everything we can give to user. 
Here we need to specify what do we want exactly. 

Main idea : tray will collect data and send to e2e plugin via wevsocket. And plugin will display that data. Also tray will store monitoring data in some local storage (like sqlite or something...) .

**Comment by akarasulu** [comment]
We basically need to pull time series information from peers, resource hosts, environments, containers about net, resource utilization, processes, load etc and manage it's aggregation locally via the tray. Tray will connect and gather via p2p and use various REST interfaces or even login and execute commands. Maybe there is a nice way we can handle this not to write nasty code in the tray. 
 
The e2e plugin when on the Hub's environment explorer web page will issue queries to the tray to pull data from the local database for this time series information to show it on the UI. Even though the UI is not defined yet (visualization technique) we know pretty much what will be displayed. Basically any and all information for users to see the almost real time dynamics of the environment they can drill deeper into to the level of application processes on a container.

**Comment by akarasulu** [comment]
Nice to also see ping distances between peers in swarm.
