### ISSUE TITLE
[Win] Undefiined VM status in tray on VirtualBox 5.1.2

### ISSUE THREAD

**Issue by btemir** [subutai-io/tray#96]
![vm_noidea](https://cloud.githubusercontent.com/assets/16958983/17773404/118975e6-6570-11e6-990c-13575d2793b1.PNG)

**Comment by NikolaiB** [comment]
Condition of Subutai VM become 'running' and buttons become active after restart VM.
![18-08-2016 18-55-04](https://cloud.githubusercontent.com/assets/11311924/17774601/9dec98b6-657e-11e6-85ae-6cb6337f19e2.jpg)

**Comment by btemir** [comment]
The same with 5.1.4. And no option to proceed in headless mode when close machine session in GUI. 
Proper state is displayed in tray after VM is powered off and then powered on, reset does not help.

**Comment by Lezh1k** [comment]
Same in linux. Need to try to update SDK .

**Comment by Lezh1k** [comment]
Virtualbox 5.1 SDK isn't compatible with virtualbox 5.0 or elder.

**Comment by Lezh1k** [comment]
Test scenario : 
1. Install virtualbox 5.1 or update existing to virtualbox 5.1 . 
2. Install subutai. 
3. Run tray application and check VM state. Should be the same as in VirtualBox Manager. Changing status should be handled in tray application.

**Comment by NikolaiB** [comment]
'no idea' label disappeared. Now status in tray the same as in VB.
