### ISSUE TITLE
Add a Notification that allows users to see who is using their peers

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#98]
When someone is using my peer I am not notified about this - and this means I can turn my peer off and the one who is using it will be unsatisfied , so I suggest : 
1. Notify when someone is using someone's peer - maybe even a request/notification  should come 
2. This way I will know that someone is using my peer and I wont turn it off, I will keep it on to satisfy the one who is using it

**Comment by amol4anoff** [comment]
There's a notification, but it doesn't show up. It is shown in front of browser window, so cant be seen if your browser window is opened on full screen. Please re-check and fix it.

**Comment by ibragim13** [comment]
Failed in Prod.

**Comment by SEFI2** [comment]
@amol4anoff I don't think that the problem of dialogs, showing up on back of the browser, refers to this issue. So as you pointed out here [https://github.com/subutai-io/tray/issues/436], it happens with other dialogs too.

**Comment by amol4anoff** [comment]
Done.
